package org.gephi.ui.statistics.plugin.social;

import javax.swing.JCheckBox;
import org.gephi.lib.validation.BetweenZeroAndOneValidator;
import org.gephi.lib.validation.IntegerIntervalValidator;
import org.gephi.lib.validation.PositiveNumberValidator;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.ValidationPanel;

/**
 *
 * @author Alexandru Topirceanu
 */
public class RandomWalkPanel extends javax.swing.JPanel {

    public RandomWalkPanel() {
        initComponents();
    }

    public static ValidationPanel createValidationPanel(RandomWalkPanel innerPanel) {
        ValidationPanel validationPanel = new ValidationPanel();
        if (innerPanel == null) {
            innerPanel = new RandomWalkPanel();
        }
        validationPanel.setInnerComponent(innerPanel);

        ValidationGroup group = validationPanel.getValidationGroup();

        // graph parameters
        group.add(innerPanel.tRepeats, Validators.REQUIRE_NON_NEGATIVE_NUMBER, new IntegerIntervalValidator(1, 10000));
        group.add(innerPanel.tMaxPath, Validators.REQUIRE_NON_NEGATIVE_NUMBER, new IntegerIntervalValidator(1, 1000));

        return validationPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        labelRandomize1 = new javax.swing.JLabel();
        desriptionLabel = new org.jdesktop.swingx.JXLabel();
        header = new org.jdesktop.swingx.JXHeader();
        labelRandomize2 = new javax.swing.JLabel();
        labelRandomize3 = new javax.swing.JLabel();
        tRepeats = new javax.swing.JTextField();
        tMaxPath = new javax.swing.JTextField();
        rStubborn = new javax.swing.JCheckBox();

        labelRandomize1.setFont(labelRandomize1.getFont().deriveFont(labelRandomize1.getFont().getSize()-1f));
        labelRandomize1.setForeground(new java.awt.Color(102, 102, 102));
        labelRandomize1.setText(org.openide.util.NbBundle.getMessage(RandomWalkPanel.class, "RandomWalkPanel.labelRandomize1.text")); // NOI18N

        setForeground(new java.awt.Color(51, 51, 255));

        desriptionLabel.setLineWrap(true);
        desriptionLabel.setText(org.openide.util.NbBundle.getMessage(RandomWalkPanel.class, "RandomWalkPanel.desriptionLabel.text")); // NOI18N
        desriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        header.setDescription(org.openide.util.NbBundle.getMessage(RandomWalkPanel.class, "RandomWalkPanel.header.description")); // NOI18N
        header.setTitle(org.openide.util.NbBundle.getMessage(RandomWalkPanel.class, "RandomWalkPanel.header.title")); // NOI18N

        labelRandomize2.setFont(labelRandomize2.getFont().deriveFont(labelRandomize2.getFont().getSize()-1f));
        labelRandomize2.setForeground(new java.awt.Color(102, 102, 102));
        labelRandomize2.setText(org.openide.util.NbBundle.getMessage(RandomWalkPanel.class, "RandomWalkPanel.labelRandomize2.text")); // NOI18N

        labelRandomize3.setFont(labelRandomize3.getFont().deriveFont(labelRandomize3.getFont().getSize()-1f));
        labelRandomize3.setForeground(new java.awt.Color(102, 102, 102));
        labelRandomize3.setText(org.openide.util.NbBundle.getMessage(RandomWalkPanel.class, "RandomWalkPanel.labelRandomize3.text")); // NOI18N

        tRepeats.setText(org.openide.util.NbBundle.getMessage(RandomWalkPanel.class, "RandomWalkPanel.tRepeats.text")); // NOI18N

        tMaxPath.setText(org.openide.util.NbBundle.getMessage(RandomWalkPanel.class, "RandomWalkPanel.tMaxPath.text")); // NOI18N

        rStubborn.setText(org.openide.util.NbBundle.getMessage(RandomWalkPanel.class, "RandomWalkPanel.rStubborn.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rStubborn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(391, 391, 391))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tRepeats, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tMaxPath, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRandomize2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelRandomize3, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRandomize2)
                    .addComponent(tRepeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRandomize3)
                    .addComponent(tMaxPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(desriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rStubborn)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private org.jdesktop.swingx.JXLabel desriptionLabel;
    private org.jdesktop.swingx.JXHeader header;
    private javax.swing.JLabel labelRandomize1;
    private javax.swing.JLabel labelRandomize2;
    private javax.swing.JLabel labelRandomize3;
    protected javax.swing.JCheckBox rStubborn;
    protected javax.swing.JTextField tMaxPath;
    protected javax.swing.JTextField tRepeats;
    // End of variables declaration//GEN-END:variables
}
