package org.gephi.ui.statistics.plugin;

import org.gephi.graph.api.GraphController;
import org.gephi.lib.validation.BetweenZeroAndOneValidator;
import org.gephi.lib.validation.IntegerIntervalValidator;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.ValidationPanel;
import org.openide.util.Lookup;

/**
 *
 * @author pjmcswee
 */
public class GirvanNewmanClustererPanel extends javax.swing.JPanel {

  /**
   * Creates new form EdgeBetweennessPanel
   */
  public GirvanNewmanClustererPanel() {
    initComponents(); 
  }
  
  public static ValidationPanel createValidationPanel(GirvanNewmanClustererPanel innerPanel) {
        ValidationPanel validationPanel = new ValidationPanel();
        if (innerPanel == null) {
            innerPanel = new GirvanNewmanClustererPanel();
        }
        validationPanel.setInnerComponent(innerPanel);

        ValidationGroup group = validationPanel.getValidationGroup();       
        group.add(innerPanel.clustersTextField, Validators.REQUIRE_NON_EMPTY_STRING, new IntegerIntervalValidator(1, 10000));
                      
        return validationPanel;
    }
  
   public int getClusters() {
        return Integer.valueOf(clustersTextField.getText());        
    }

    public void setClusters(int clusters) {
        clustersTextField.setText(String.valueOf(clusters));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        header = new org.jdesktop.swingx.JXHeader();
        clustersTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        header.setDescription(org.openide.util.NbBundle.getMessage(GirvanNewmanClustererPanel.class, "GirvanNewmanClustererPanel.header.description_2")); // NOI18N
        header.setTitle(org.openide.util.NbBundle.getMessage(GirvanNewmanClustererPanel.class, "GirvanNewmanClustererPanel.header.title_2")); // NOI18N

        clustersTextField.setText(org.openide.util.NbBundle.getMessage(GirvanNewmanClustererPanel.class, "GirvanNewmanClustererPanel.clustersTextField.text")); // NOI18N
        clustersTextField.setToolTipText(org.openide.util.NbBundle.getMessage(GirvanNewmanClustererPanel.class, "GirvanNewmanClustererPanel.clustersTextField.toolTipText")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(GirvanNewmanClustererPanel.class, "GirvanNewmanClustererPanel.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clustersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clustersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    protected javax.swing.JTextField clustersTextField;
    private org.jdesktop.swingx.JXHeader header;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
