package org.gephi.ui.statistics.plugin;

import org.gephi.graph.api.GraphController;
import org.openide.util.Lookup;

/**
 *
 * @author Alexander
 */
public class InfluenceRankingsPanel extends javax.swing.JPanel {

    public InfluenceRankingsPanel() {
        initComponents();
        
        //Disable directed if the graph is undirecteds
        GraphController graphController = Lookup.getDefault().lookup(GraphController.class);
        if(graphController.getModel().isUndirected()){
            directedRadioButton.setEnabled(false);
        }
    }

    public boolean isDirected() {
        return directedRadioButton.isSelected();
    }
   
    public boolean isEdgeWeight() {
        return edgeWeightCheckbox.isSelected();
    }

    public void setEdgeWeight(boolean edgeWeight) {
        edgeWeightCheckbox.setSelected(edgeWeight);
    }

    public void setDirected(boolean directed) {
        directedButtonGroup.setSelected(directed ? directedRadioButton.getModel() : undirectedRadioButton.getModel(), true);
        if (!directed) {
            directedRadioButton.setEnabled(false);
        }
    }  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        directedButtonGroup = new javax.swing.ButtonGroup();
        metricsGroup = new javax.swing.ButtonGroup();
        undirectedRadioButton = new javax.swing.JRadioButton();
        directedRadioButton = new javax.swing.JRadioButton();
        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        edgeWeightCheckbox = new javax.swing.JCheckBox();
        radioHirsch = new javax.swing.JRadioButton();
        radioLeaderRank = new javax.swing.JRadioButton();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        radioClusterRank = new javax.swing.JRadioButton();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        radioLocalCentrality = new javax.swing.JRadioButton();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        radioEdgeCentrality = new javax.swing.JRadioButton();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();

        directedButtonGroup.add(undirectedRadioButton);
        undirectedRadioButton.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.undirectedRadioButton.text")); // NOI18N

        directedButtonGroup.add(directedRadioButton);
        directedRadioButton.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.directedRadioButton.text")); // NOI18N

        jXHeader1.setDescription(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.jXHeader1.description")); // NOI18N
        jXHeader1.setTitle(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.jXHeader1.title")); // NOI18N

        edgeWeightCheckbox.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.edgeWeightCheckbox.text")); // NOI18N
        edgeWeightCheckbox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        metricsGroup.add(radioHirsch);
        radioHirsch.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.radioHirsch.text")); // NOI18N

        metricsGroup.add(radioLeaderRank);
        radioLeaderRank.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.radioLeaderRank.text")); // NOI18N
        radioLeaderRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLeaderRankActionPerformed(evt);
            }
        });

        jXLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jXLabel3.setLineWrap(true);
        jXLabel3.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.jXLabel3.text")); // NOI18N
        jXLabel3.setFont(jXLabel3.getFont().deriveFont(jXLabel3.getFont().getSize()-1f));

        jXLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jXLabel4.setLineWrap(true);
        jXLabel4.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.jXLabel4.text")); // NOI18N
        jXLabel4.setFont(jXLabel4.getFont().deriveFont(jXLabel4.getFont().getSize()-1f));

        metricsGroup.add(radioClusterRank);
        radioClusterRank.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.radioClusterRank.text")); // NOI18N

        jXLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jXLabel5.setLineWrap(true);
        jXLabel5.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.jXLabel5.text")); // NOI18N
        jXLabel5.setFont(jXLabel5.getFont().deriveFont(jXLabel5.getFont().getSize()-1f));

        metricsGroup.add(radioLocalCentrality);
        radioLocalCentrality.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.radioLocalCentrality.text")); // NOI18N

        jXLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jXLabel6.setLineWrap(true);
        jXLabel6.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.jXLabel6.text")); // NOI18N
        jXLabel6.setFont(jXLabel6.getFont().deriveFont(jXLabel6.getFont().getSize()-1f));

        jXLabel7.setLineWrap(true);
        jXLabel7.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.jXLabel7.text")); // NOI18N
        jXLabel7.setFont(jXLabel7.getFont().deriveFont(jXLabel7.getFont().getSize()-1f));

        metricsGroup.add(radioEdgeCentrality);
        radioEdgeCentrality.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.radioEdgeCentrality.text")); // NOI18N

        jXLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jXLabel8.setLineWrap(true);
        jXLabel8.setText(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.jXLabel8.text")); // NOI18N
        jXLabel8.setFont(jXLabel8.getFont().deriveFont(jXLabel8.getFont().getSize()-1f));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directedRadioButton)
                    .addComponent(undirectedRadioButton))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(edgeWeightCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jXLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jXLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jXLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(radioEdgeCentrality)
                            .addComponent(radioClusterRank)
                            .addComponent(radioHirsch)
                            .addComponent(radioLeaderRank)
                            .addComponent(radioLocalCentrality))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(directedRadioButton)
                    .addComponent(radioHirsch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(undirectedRadioButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioLeaderRank)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioClusterRank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioLocalCentrality)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioEdgeCentrality)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edgeWeightCheckbox)
                    .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXLabel4.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.jXLabel4.AccessibleContext.accessibleName")); // NOI18N
        jXLabel7.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(InfluenceRankingsPanel.class, "InfluenceRankingsPanel.jXLabel7.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void radioLeaderRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLeaderRankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLeaderRankActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup directedButtonGroup;
    protected javax.swing.JRadioButton directedRadioButton;
    private javax.swing.JCheckBox edgeWeightCheckbox;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private javax.swing.ButtonGroup metricsGroup;
    protected javax.swing.JRadioButton radioClusterRank;
    protected javax.swing.JRadioButton radioEdgeCentrality;
    protected javax.swing.JRadioButton radioHirsch;
    protected javax.swing.JRadioButton radioLeaderRank;
    protected javax.swing.JRadioButton radioLocalCentrality;
    protected javax.swing.JRadioButton undirectedRadioButton;
    // End of variables declaration//GEN-END:variables
}
